### ISSUE TITLE
What is the source of html attribute this repo rely on?

### ISSUE THREAD

**Issue by Thaina** [kjpou1/wasm-dom#2]
I means, which document you have used to generate (or manual written) each HTMLElement class?

And according to w3c and mozilla, I think `NoWrap` attribute only exist in HTMLCellElement but not on any other element. However it exist in Div and Body in this repo

https://github.com/kjpou1/wasm-dom/blob/36366f731302561d98f3a77264a7e220b6f0afca/Mono.WebAssembly.Browser/DOM/Interfaces.cs#L1010-L1018

**Comment by kjpou1** [comment]
Hello Thaina

The code is being generated off the typescript definitions that can be found here:

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts

The code for HTMLDivElement interface is found here: 
 https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L5440

It defines the noWrap  as the following:

```
    /**
     * Sets or retrieves whether the browser automatically performs wordwrap.
     */
    noWrap: boolean;
```

And extends the HTMLElement interface.

**Comment by Thaina** [comment]
@kjpou1 Will the webgl dom for C# would also be generated this way?
