### ISSUE TITLE
Sdk missing

### ISSUE THREAD

**Issue by LunicLynx** [kjpou1/wasm-dom#6]
Hello the sdk referenced by the Makefile does not exist anymore:

https://jenkins.mono-project.com/job/test-mono-mainline-wasm/1219/label=ubuntu-1804-amd64/Azure/processDownloadRequest/1219/ubuntu-1804-amd64/sdks/wasm/mono-wasm-0beb0875670.zip

How can this be fixed?

**Comment by VBAndCs** [comment]
Try the latest build:
https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/processDownloadRequest/5045/ubuntu-1804-amd64/sdks/wasm/mono-wasm-88cae11c6b7.zip

**Comment by LunicLynx** [comment]
Thank you that helped!

Happy 🎁 🎄
